//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tabsh {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Res {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Res() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Tabsh.Res", typeof(Res).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; is not recognized as an internal or external command, operable program or batch file..
        /// </summary>
        internal static string CommandNotRecognized {
            get {
                return ResourceManager.GetString("CommandNotRecognized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The syntax of the command is incorrect..
        /// </summary>
        internal static string SyntaxIncorrect {
            get {
                return ResourceManager.GetString("SyntaxIncorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The system cannot find the path specified: {0}.
        /// </summary>
        internal static string PathNotFound {
            get {
                return ResourceManager.GetString("PathNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The system cannot find the file specified: {0}.
        /// </summary>
        internal static string FileNotFound {
            get {
                return ResourceManager.GetString("FileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Not Found.
        /// </summary>
        internal static string FileNotFoundShort {
            get {
                return ResourceManager.GetString("FileNotFoundShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overwrite {0}? .
        /// </summary>
        internal static string OverwriteFile {
            get {
                return ResourceManager.GetString("OverwriteFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete {0}? .
        /// </summary>
        internal static string DeleteFile {
            get {
                return ResourceManager.GetString("DeleteFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}, are you sure? .
        /// </summary>
        internal static string DeleteEverything {
            get {
                return ResourceManager.GetString("DeleteEverything", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}, are you sure? .
        /// </summary>
        internal static string RemoveTree {
            get {
                return ResourceManager.GetString("RemoveTree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could Not Find {0}.
        /// </summary>
        internal static string CouldNotFind {
            get {
                return ResourceManager.GetString("CouldNotFind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not valid base64: {0}.
        /// </summary>
        internal static string InvalidBase64 {
            get {
                return ResourceManager.GetString("InvalidBase64", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid width: {0}.
        /// </summary>
        internal static string InvalidWidth {
            get {
                return ResourceManager.GetString("InvalidWidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only one input can be written to a file..
        /// </summary>
        internal static string OneInputExpected {
            get {
                return ResourceManager.GetString("OneInputExpected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid count: {0}.
        /// </summary>
        internal static string InvalidCount {
            get {
                return ResourceManager.GetString("InvalidCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to At most {0} at a time..
        /// </summary>
        internal static string CountTooLarge {
            get {
                return ResourceManager.GetString("CountTooLarge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid format: {0}.
        /// </summary>
        internal static string InvalidFormat {
            get {
                return ResourceManager.GetString("InvalidFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid algorithm: {0}. One of: {1}.
        /// </summary>
        internal static string InvalidAlgorithm {
            get {
                return ResourceManager.GetString("InvalidAlgorithm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is not supported by this Windows..
        /// </summary>
        internal static string AlgorithmNotSupported {
            get {
                return ResourceManager.GetString("AlgorithmNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid switch - {0}.
        /// </summary>
        internal static string InvalidSwitch {
            get {
                return ResourceManager.GetString("InvalidSwitch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; is not a file descriptor..
        /// </summary>
        internal static string NotAFileDescriptor {
            get {
                return ResourceManager.GetString("NotAFileDescriptor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Environment variable {0} not defined..
        /// </summary>
        internal static string VariableNotDefined {
            get {
                return ResourceManager.GetString("VariableNotDefined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; is not an alias..
        /// </summary>
        internal static string NotAnAlias {
            get {
                return ResourceManager.GetString("NotAnAlias", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A colour is two hexadecimal digits, background then foreground..
        /// </summary>
        internal static string ColourExpected {
            get {
                return ResourceManager.GetString("ColourExpected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A name is expected..
        /// </summary>
        internal static string NameExpected {
            get {
                return ResourceManager.GetString("NameExpected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INFO: Could not find files for the given pattern(s)..
        /// </summary>
        internal static string NoFilesFound {
            get {
                return ResourceManager.GetString("NoFilesFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A directory is expected after /R..
        /// </summary>
        internal static string DirectoryExpected {
            get {
                return ResourceManager.GetString("DirectoryExpected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0,10}   {1,-13}   {2}  {3}.
        /// </summary>
        internal static string WhereDetailLine {
            get {
                return ResourceManager.GetString("WhereDetailLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}: built in.
        /// </summary>
        internal static string BuiltInMarker {
            get {
                return ResourceManager.GetString("BuiltInMarker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; was not expected here..
        /// </summary>
        internal static string UnexpectedToken {
            get {
                return ResourceManager.GetString("UnexpectedToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to a command was expected before &apos;{0}&apos;..
        /// </summary>
        internal static string CommandExpectedBefore {
            get {
                return ResourceManager.GetString("CommandExpectedBefore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to a command was expected after &apos;|&apos;..
        /// </summary>
        internal static string CommandExpectedAfterPipe {
            get {
                return ResourceManager.GetString("CommandExpectedAfterPipe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;)&apos; was expected..
        /// </summary>
        internal static string ClosingParenthesisExpected {
            get {
                return ResourceManager.GetString("ClosingParenthesisExpected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to a file name was expected after &apos;{0}&apos;..
        /// </summary>
        internal static string FileNameExpectedAfter {
            get {
                return ResourceManager.GetString("FileNameExpectedAfter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to end of line.
        /// </summary>
        internal static string EndOfLine {
            get {
                return ResourceManager.GetString("EndOfLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;DIR&gt;.
        /// </summary>
        internal static string DirectoryMarker {
            get {
                return ResourceManager.GetString("DirectoryMarker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;ITEM&gt;.
        /// </summary>
        internal static string ItemMarker {
            get {
                return ResourceManager.GetString("ItemMarker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;JUNCTION&gt;.
        /// </summary>
        internal static string JunctionMarker {
            get {
                return ResourceManager.GetString("JunctionMarker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;SYMLINK&gt;.
        /// </summary>
        internal static string SymlinkMarker {
            get {
                return ResourceManager.GetString("SymlinkMarker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;SYMLINKD&gt;.
        /// </summary>
        internal static string SymlinkDirectoryMarker {
            get {
                return ResourceManager.GetString("SymlinkDirectoryMarker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  [{0}].
        /// </summary>
        internal static string LinkTargetSuffix {
            get {
                return ResourceManager.GetString("LinkTargetSuffix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0,37:N0}  {1}.
        /// </summary>
        internal static string StreamLine {
            get {
                return ResourceManager.GetString("StreamLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0,17} {1}  {2}.
        /// </summary>
        internal static string ShellEntryLine {
            get {
                return ResourceManager.GetString("ShellEntryLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Properties of {0}.
        /// </summary>
        internal static string PropertiesOf {
            get {
                return ResourceManager.GetString("PropertiesOf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}  {1}.
        /// </summary>
        internal static string PropertyLine {
            get {
                return ResourceManager.GetString("PropertyLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0,16} value(s).
        /// </summary>
        internal static string PropertyCount {
            get {
                return ResourceManager.GetString("PropertyCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No file or item matches: {0}.
        /// </summary>
        internal static string NoMatch {
            get {
                return ResourceManager.GetString("NoMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No property store: {0}.
        /// </summary>
        internal static string NoProperties {
            get {
                return ResourceManager.GetString("NoProperties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {{{0}}} {1}.
        /// </summary>
        internal static string RawPropertyKey {
            get {
                return ResourceManager.GetString("RawPropertyKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0,16} item(s).
        /// </summary>
        internal static string ShellItemCount {
            get {
                return ResourceManager.GetString("ShellItemCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Volume in drive {0} is {1}.
        /// </summary>
        internal static string VolumeInDrive {
            get {
                return ResourceManager.GetString("VolumeInDrive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Directory of {0}.
        /// </summary>
        internal static string DirectoryOf {
            get {
                return ResourceManager.GetString("DirectoryOf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0,16} File(s) {1,15:N0} bytes.
        /// </summary>
        internal static string FileCountSummary {
            get {
                return ResourceManager.GetString("FileCountSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0,16} Dir(s) {1,16:N0} bytes free.
        /// </summary>
        internal static string DirectoryCountSummary {
            get {
                return ResourceManager.GetString("DirectoryCountSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0,8} file(s) copied..
        /// </summary>
        internal static string FilesCopied {
            get {
                return ResourceManager.GetString("FilesCopied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0,8} file(s) moved..
        /// </summary>
        internal static string FilesMoved {
            get {
                return ResourceManager.GetString("FilesMoved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Built in commands, everything else is looked for on PATH..
        /// </summary>
        internal static string HelpHeader {
            get {
                return ResourceManager.GetString("HelpHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TAB cycles through the names that match, directories first and with a trailing separator..
        /// </summary>
        internal static string HelpTab {
            get {
                return ResourceManager.GetString("HelpTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shift+TAB goes back through them, ESC puts back what you had typed..
        /// </summary>
        internal static string HelpShiftTab {
            get {
                return ResourceManager.GetString("HelpShiftTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A line that is nothing but the name of a directory changes to it..
        /// </summary>
        internal static string HelpAutoCd {
            get {
                return ResourceManager.GetString("HelpAutoCd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One process is still running:.
        /// </summary>
        internal static string OneProcessRunning {
            get {
                return ResourceManager.GetString("OneProcessRunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} processes are still running:.
        /// </summary>
        internal static string ProcessesRunning {
            get {
                return ResourceManager.GetString("ProcessesRunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terminate all of them (Y/N)? .
        /// </summary>
        internal static string TerminatePrompt {
            get {
                return ResourceManager.GetString("TerminatePrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Y.
        /// </summary>
        internal static string YesKey {
            get {
                return ResourceManager.GetString("YesKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to N.
        /// </summary>
        internal static string NoKey {
            get {
                return ResourceManager.GetString("NoKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input mode.
        /// </summary>
        internal static string LabelConsoleInputMode {
            get {
                return ResourceManager.GetString("LabelConsoleInputMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output mode.
        /// </summary>
        internal static string LabelConsoleOutputMode {
            get {
                return ResourceManager.GetString("LabelConsoleOutputMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Virtual terminal.
        /// </summary>
        internal static string LabelVirtualTerminal {
            get {
                return ResourceManager.GetString("LabelVirtualTerminal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code page.
        /// </summary>
        internal static string LabelCodePage {
            get {
                return ResourceManager.GetString("LabelCodePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0x{0:X4}.
        /// </summary>
        internal static string ConsoleMode {
            get {
                return ResourceManager.GetString("ConsoleMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} in, {1} out.
        /// </summary>
        internal static string CodePageLine {
            get {
                return ResourceManager.GetString("CodePageLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to on, escape sequences are obeyed.
        /// </summary>
        internal static string VirtualTerminalOn {
            get {
                return ResourceManager.GetString("VirtualTerminalOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to refused, escape sequences will be printed as text.
        /// </summary>
        internal static string VirtualTerminalOff {
            get {
                return ResourceManager.GetString("VirtualTerminalOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This console does not support it. A console with &quot;Use legacy console&quot; ticked never will, and neither does one older than Windows 10. Untick it in the console properties and open a new window..
        /// </summary>
        internal static string VirtualTerminalHint {
            get {
                return ResourceManager.GetString("VirtualTerminalHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no console here, the output is going somewhere else..
        /// </summary>
        internal static string NoConsole {
            get {
                return ResourceManager.GetString("NoConsole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to shows the console modes, which is what decides whether colour works..
        /// </summary>
        internal static string DescribeConsole {
            get {
                return ResourceManager.GetString("DescribeConsole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only the command itself can be ended here, anything it started will keep running..
        /// </summary>
        internal static string TreeCannotBeKilled {
            get {
                return ResourceManager.GetString("TreeCannotBeKilled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (nothing could be read).
        /// </summary>
        internal static string ProcessUnreadable {
            get {
                return ResourceManager.GetString("ProcessUnreadable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (running elevated, cannot be read from here).
        /// </summary>
        internal static string ProcessElevated {
            get {
                return ResourceManager.GetString("ProcessElevated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (already ended).
        /// </summary>
        internal static string ProcessEnded {
            get {
                return ResourceManager.GetString("ProcessEnded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (cannot be opened, error {0}).
        /// </summary>
        internal static string ProcessOpenFailed {
            get {
                return ResourceManager.GetString("ProcessOpenFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} {1} [Version {2}].
        /// </summary>
        internal static string ProductHeadline {
            get {
                return ResourceManager.GetString("ProductHeadline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} [Version {1}].
        /// </summary>
        internal static string BannerHeadline {
            get {
                return ResourceManager.GetString("BannerHeadline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Microsoft {0} [Version {1}].
        /// </summary>
        internal static string WindowsHeadline {
            get {
                return ResourceManager.GetString("WindowsHeadline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Windows.
        /// </summary>
        internal static string WindowsUnknown {
            get {
                return ResourceManager.GetString("WindowsUnknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edition.
        /// </summary>
        internal static string LabelEdition {
            get {
                return ResourceManager.GetString("LabelEdition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version.
        /// </summary>
        internal static string LabelVersion {
            get {
                return ResourceManager.GetString("LabelVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installed on.
        /// </summary>
        internal static string LabelInstalledOn {
            get {
                return ResourceManager.GetString("LabelInstalledOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OS build.
        /// </summary>
        internal static string LabelOsBuild {
            get {
                return ResourceManager.GetString("LabelOsBuild", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Experience.
        /// </summary>
        internal static string LabelExperience {
            get {
                return ResourceManager.GetString("LabelExperience", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System type.
        /// </summary>
        internal static string LabelSystemType {
            get {
                return ResourceManager.GetString("LabelSystemType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 64-bit operating system.
        /// </summary>
        internal static string OperatingSystem64 {
            get {
                return ResourceManager.GetString("OperatingSystem64", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 32-bit operating system.
        /// </summary>
        internal static string OperatingSystem32 {
            get {
                return ResourceManager.GetString("OperatingSystem32", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to x64-based processor.
        /// </summary>
        internal static string ProcessorX64 {
            get {
                return ResourceManager.GetString("ProcessorX64", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to x86-based processor.
        /// </summary>
        internal static string ProcessorX86 {
            get {
                return ResourceManager.GetString("ProcessorX86", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ARM64-based processor.
        /// </summary>
        internal static string ProcessorArm64 {
            get {
                return ResourceManager.GetString("ProcessorArm64", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ARM-based processor.
        /// </summary>
        internal static string ProcessorArm {
            get {
                return ResourceManager.GetString("ProcessorArm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}-based processor.
        /// </summary>
        internal static string ProcessorOther {
            get {
                return ResourceManager.GetString("ProcessorOther", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}, {1}.
        /// </summary>
        internal static string SystemTypeAndProcessor {
            get {
                return ResourceManager.GetString("SystemTypeAndProcessor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  ({0} process).
        /// </summary>
        internal static string ProcessArchitectureNote {
            get {
                return ResourceManager.GetString("ProcessArchitectureNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}={1}.
        /// </summary>
        internal static string NameValueLine {
            get {
                return ResourceManager.GetString("NameValueLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PATH={0}.
        /// </summary>
        internal static string PathLine {
            get {
                return ResourceManager.GetString("PathLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to   {0,-10} {1}.
        /// </summary>
        internal static string HelpLine {
            get {
                return ResourceManager.GetString("HelpLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to              tokens, written {Name} and replaced every prompt: {0}.
        /// </summary>
        internal static string TokenList {
            get {
                return ResourceManager.GetString("TokenList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Administrator.
        /// </summary>
        internal static string TitleAdministrator {
            get {
                return ResourceManager.GetString("TitleAdministrator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0,5}  {1}.
        /// </summary>
        internal static string HistoryLine {
            get {
                return ResourceManager.GetString("HistoryLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A command is expected..
        /// </summary>
        internal static string CommandExpected {
            get {
                return ResourceManager.GetString("CommandExpected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nothing was started, so there is nothing else to report..
        /// </summary>
        internal static string NothingMeasured {
            get {
                return ResourceManager.GetString("NothingMeasured", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No job held this command, so anything it started is not counted here..
        /// </summary>
        internal static string TreeNotMeasured {
            get {
                return ResourceManager.GetString("TreeNotMeasured", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Elapsed.
        /// </summary>
        internal static string LabelElapsed {
            get {
                return ResourceManager.GetString("LabelElapsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit code.
        /// </summary>
        internal static string LabelExitCode {
            get {
                return ResourceManager.GetString("LabelExitCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processes.
        /// </summary>
        internal static string LabelProcesses {
            get {
                return ResourceManager.GetString("LabelProcesses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User time.
        /// </summary>
        internal static string LabelUserTime {
            get {
                return ResourceManager.GetString("LabelUserTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kernel time.
        /// </summary>
        internal static string LabelKernelTime {
            get {
                return ResourceManager.GetString("LabelKernelTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processor time.
        /// </summary>
        internal static string LabelCpuTime {
            get {
                return ResourceManager.GetString("LabelCpuTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processor share.
        /// </summary>
        internal static string LabelCpuShare {
            get {
                return ResourceManager.GetString("LabelCpuShare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Peak memory.
        /// </summary>
        internal static string LabelPeakJobMemory {
            get {
                return ResourceManager.GetString("LabelPeakJobMemory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Peak working set.
        /// </summary>
        internal static string LabelPeakWorkingSet {
            get {
                return ResourceManager.GetString("LabelPeakWorkingSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page faults.
        /// </summary>
        internal static string LabelPageFaults {
            get {
                return ResourceManager.GetString("LabelPageFaults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Graphics time.
        /// </summary>
        internal static string LabelGpuTime {
            get {
                return ResourceManager.GetString("LabelGpuTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Graphics memory.
        /// </summary>
        internal static string LabelGpuMemory {
            get {
                return ResourceManager.GetString("LabelGpuMemory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bytes read.
        /// </summary>
        internal static string LabelBytesRead {
            get {
                return ResourceManager.GetString("LabelBytesRead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bytes written.
        /// </summary>
        internal static string LabelBytesWritten {
            get {
                return ResourceManager.GetString("LabelBytesWritten", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bytes other.
        /// </summary>
        internal static string LabelBytesOther {
            get {
                return ResourceManager.GetString("LabelBytesOther", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operations.
        /// </summary>
        internal static string LabelOperations {
            get {
                return ResourceManager.GetString("LabelOperations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0:N1} ms.
        /// </summary>
        internal static string MillisecondValue {
            get {
                return ResourceManager.GetString("MillisecondValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0:N3} s.
        /// </summary>
        internal static string SecondValue {
            get {
                return ResourceManager.GetString("SecondValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0:N1} %.
        /// </summary>
        internal static string PercentValue {
            get {
                return ResourceManager.GetString("PercentValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0:N0} B.
        /// </summary>
        internal static string ByteValue {
            get {
                return ResourceManager.GetString("ByteValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0:N2} {1}.
        /// </summary>
        internal static string ScaledByteValue {
            get {
                return ResourceManager.GetString("ScaledByteValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Holding {0}.
        /// </summary>
        internal static string HoldingLine {
            get {
                return ResourceManager.GetString("HoldingLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The clipboard holds no text..
        /// </summary>
        internal static string ClipboardEmpty {
            get {
                return ResourceManager.GetString("ClipboardEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The clipboard could not be opened..
        /// </summary>
        internal static string ClipboardUnavailable {
            get {
                return ResourceManager.GetString("ClipboardUnavailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Act on which? all, a number, or nothing: .
        /// </summary>
        internal static string ActPrompt {
            get {
                return ResourceManager.GetString("ActPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [C]lose, [R]estart or [T]erminate? .
        /// </summary>
        internal static string ActionPrompt {
            get {
                return ResourceManager.GetString("ActionPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C.
        /// </summary>
        internal static string ActionCloseKey {
            get {
                return ResourceManager.GetString("ActionCloseKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to R.
        /// </summary>
        internal static string ActionRestartKey {
            get {
                return ResourceManager.GetString("ActionRestartKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to T.
        /// </summary>
        internal static string ActionTerminateKey {
            get {
                return ResourceManager.GetString("ActionTerminateKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to all.
        /// </summary>
        internal static string ActAllKey {
            get {
                return ResourceManager.GetString("ActAllKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Done..
        /// </summary>
        internal static string ActDone {
            get {
                return ResourceManager.GetString("ActDone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It did not work, error {0}..
        /// </summary>
        internal static string ActFailed {
            get {
                return ResourceManager.GetString("ActFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choosing needs a console. Name the action with /k:c, /k:r or /k:t, and /f to skip the asking..
        /// </summary>
        internal static string ActNeedsConsole {
            get {
                return ResourceManager.GetString("ActNeedsConsole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to   {0,3}  {1,6}  {2}.
        /// </summary>
        internal static string NumberedProcessLine {
            get {
                return ResourceManager.GetString("NumberedProcessLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stopped at {0} matches..
        /// </summary>
        internal static string MatchLimit {
            get {
                return ResourceManager.GetString("MatchLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nothing is holding it..
        /// </summary>
        internal static string NothingHolding {
            get {
                return ResourceManager.GetString("NothingHolding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to   {0,6}  {1}.
        /// </summary>
        internal static string ProcessLine {
            get {
                return ResourceManager.GetString("ProcessLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to   {0}{1}.
        /// </summary>
        internal static string SpecificationLine {
            get {
                return ResourceManager.GetString("SpecificationLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{0}].
        /// </summary>
        internal static string WideDirectory {
            get {
                return ResourceManager.GetString("WideDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0,-12} {1}.
        /// </summary>
        internal static string ShortNameLine {
            get {
                return ResourceManager.GetString("ShortNameLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0,-22} {1}.
        /// </summary>
        internal static string OwnerLine {
            get {
                return ResourceManager.GetString("OwnerLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press any key to continue . . . .
        /// </summary>
        internal static string PressAnyKey {
            get {
                return ResourceManager.GetString("PressAnyKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0:dd/MM/yyyy  HH:mm} {1}  {2}.
        /// </summary>
        internal static string DirectoryEntryLine {
            get {
                return ResourceManager.GetString("DirectoryEntryLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{0}] cursor {1}.
        /// </summary>
        internal static string KeysResult {
            get {
                return ResourceManager.GetString("KeysResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to shows the macros, or defines one as name=text..
        /// </summary>
        internal static string DescribeAlias {
            get {
                return ResourceManager.GetString("DescribeAlias", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to encodes a file, or the text itself when the name is not one. /d decodes, /o: writes to a file, /w: wraps, /t forces text..
        /// </summary>
        internal static string DescribeBase64 {
            get {
                return ResourceManager.GetString("DescribeBase64", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to shows the current directory, or changes to one. cd - goes back..
        /// </summary>
        internal static string DescribeCd {
            get {
                return ResourceManager.GetString("DescribeCd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to shows everything on the clipboard, or sets it from a pipe or from what follows. /v pastes text, /f writes the item paths, /c clears, /m watches..
        /// </summary>
        internal static string DescribeClip {
            get {
                return ResourceManager.GetString("DescribeClip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Clipboard.
        /// </summary>
        internal static string ClipboardHeader {
            get {
                return ResourceManager.GetString("ClipboardHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Items.
        /// </summary>
        internal static string ClipboardItems {
            get {
                return ResourceManager.GetString("ClipboardItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to   {0}.
        /// </summary>
        internal static string ClipboardItemLine {
            get {
                return ResourceManager.GetString("ClipboardItemLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to   {0} {1}  {2}.
        /// </summary>
        internal static string ClipboardFormatLine {
            get {
                return ResourceManager.GetString("ClipboardFormatLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The clipboard names no file or shell item..
        /// </summary>
        internal static string ClipboardNoItems {
            get {
                return ResourceManager.GetString("ClipboardNoItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (not rendered).
        /// </summary>
        internal static string NotRendered {
            get {
                return ResourceManager.GetString("NotRendered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;{0}&quot;.
        /// </summary>
        internal static string QuotedValue {
            get {
                return ResourceManager.GetString("QuotedValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} (0x{1:X8}).
        /// </summary>
        internal static string NumberValue {
            get {
                return ResourceManager.GetString("NumberValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ....
        /// </summary>
        internal static string Ellipsis {
            get {
                return ResourceManager.GetString("Ellipsis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} described file(s).
        /// </summary>
        internal static string DescriptorCount {
            get {
                return ResourceManager.GetString("DescriptorCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}, &quot;{1}&quot;, &quot;{2}&quot;.
        /// </summary>
        internal static string DropDescriptionValue {
            get {
                return ResourceManager.GetString("DropDescriptionValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to image {0}, layered {1}, offset {2},{3}.
        /// </summary>
        internal static string DragContextValue {
            get {
                return ResourceManager.GetString("DragContextValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} x {1}, offset {2},{3}, colour key 0x{4:X8}.
        /// </summary>
        internal static string DragImageValue {
            get {
                return ResourceManager.GetString("DragImageValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to copy.
        /// </summary>
        internal static string EffectCopy {
            get {
                return ResourceManager.GetString("EffectCopy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to move.
        /// </summary>
        internal static string EffectMove {
            get {
                return ResourceManager.GetString("EffectMove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to link.
        /// </summary>
        internal static string EffectLink {
            get {
                return ResourceManager.GetString("EffectLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to none.
        /// </summary>
        internal static string EffectNone {
            get {
                return ResourceManager.GetString("EffectNone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to clears the screen..
        /// </summary>
        internal static string DescribeCls {
            get {
                return ResourceManager.GetString("DescribeCls", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sets the screen colours, two hexadecimal digits..
        /// </summary>
        internal static string DescribeColor {
            get {
                return ResourceManager.GetString("DescribeColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to shows what TAB would offer for the rest of the line..
        /// </summary>
        internal static string DescribeComplete {
            get {
                return ResourceManager.GetString("DescribeComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to copies files. /y overwrites without asking, /-y always asks..
        /// </summary>
        internal static string DescribeCopy {
            get {
                return ResourceManager.GetString("DescribeCopy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to deletes files. /s recurses, /f clears the read only attribute, /p asks each time, /q asks nothing, /a: selects by attribute..
        /// </summary>
        internal static string DescribeDel {
            get {
                return ResourceManager.GetString("DescribeDel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to lists a directory. /b bare, /w and /d in columns, /p a screenful at a time, /s recurses, /a: selects by attribute, /o sorts, /t: picks the time, /l lowercases, /q owners, /x short names, /r data streams..
        /// </summary>
        internal static string DescribeDir {
            get {
                return ResourceManager.GetString("DescribeDir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to writes its arguments..
        /// </summary>
        internal static string DescribeEcho {
            get {
                return ResourceManager.GetString("DescribeEcho", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ends the shell, with an exit code if one is given..
        /// </summary>
        internal static string DescribeExit {
            get {
                return ResourceManager.GetString("DescribeExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to generates GUIDs. A number says how many, /f: picks the format N D B P X, /u uppercases..
        /// </summary>
        internal static string DescribeGuid {
            get {
                return ResourceManager.GetString("DescribeGuid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hashes a file, or the text itself when the name is not one. /a: picks the algorithm, /f: hex or base64, /u uppercases, /t forces text..
        /// </summary>
        internal static string DescribeHash {
            get {
                return ResourceManager.GetString("DescribeHash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to lists these commands..
        /// </summary>
        internal static string DescribeHelp {
            get {
                return ResourceManager.GetString("DescribeHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to shows the command history. -c clears it..
        /// </summary>
        internal static string DescribeHistory {
            get {
                return ResourceManager.GetString("DescribeHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to runs a key script through the line editor and shows the result..
        /// </summary>
        internal static string DescribeKeys {
            get {
                return ResourceManager.GetString("DescribeKeys", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to shows which processes are holding something open. A name with no path is looked for among what is loaded. /m watches, /k closes them, /f asks nothing..
        /// </summary>
        internal static string DescribeLock {
            get {
                return ResourceManager.GetString("DescribeLock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to runs a command and reports what it cost, in time, processor, memory, disk and graphics card. /p leaves out what it started..
        /// </summary>
        internal static string DescribeMeasure {
            get {
                return ResourceManager.GetString("DescribeMeasure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to creates directories, including any missing parent..
        /// </summary>
        internal static string DescribeMd {
            get {
                return ResourceManager.GetString("DescribeMd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to moves files and directories. /y overwrites without asking, /-y always asks..
        /// </summary>
        internal static string DescribeMove {
            get {
                return ResourceManager.GetString("DescribeMove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to shows or sets PATH..
        /// </summary>
        internal static string DescribePath {
            get {
                return ResourceManager.GetString("DescribePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to returns to the directory pushd left..
        /// </summary>
        internal static string DescribePopd {
            get {
                return ResourceManager.GetString("DescribePopd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to shows or sets the prompt, using cmd&apos;s $ codes..
        /// </summary>
        internal static string DescribePrompt {
            get {
                return ResourceManager.GetString("DescribePrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to remembers the current directory and changes to another..
        /// </summary>
        internal static string DescribePushd {
            get {
                return ResourceManager.GetString("DescribePushd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to writes the current directory..
        /// </summary>
        internal static string DescribePwd {
            get {
                return ResourceManager.GetString("DescribePwd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to removes directories. /s removes the contents too, /q does it without asking..
        /// </summary>
        internal static string DescribeRd {
            get {
                return ResourceManager.GetString("DescribeRd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to renames a file or a directory in place..
        /// </summary>
        internal static string DescribeRen {
            get {
                return ResourceManager.GetString("DescribeRen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to shows or sets variables. set /p name=text reads one in, set /a works one out..
        /// </summary>
        internal static string DescribeSet {
            get {
                return ResourceManager.GetString("DescribeSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to starts a program in a console of its own, or opens a document..
        /// </summary>
        internal static string DescribeStart {
            get {
                return ResourceManager.GetString("DescribeStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sets the console title..
        /// </summary>
        internal static string DescribeTitle {
            get {
                return ResourceManager.GetString("DescribeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to writes the contents of files..
        /// </summary>
        internal static string DescribeType {
            get {
                return ResourceManager.GetString("DescribeType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to shows what this Windows is, in as much detail as it will admit to..
        /// </summary>
        internal static string DescribeVer {
            get {
                return ResourceManager.GetString("DescribeVer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to shows everything the shell knows about a file or a namespace item..
        /// </summary>
        internal static string DescribeProps {
            get {
                return ResourceManager.GetString("DescribeProps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to shows every place a name resolves to. /R searches a tree, /Q is the exit code only, /F quotes, /T adds size and date..
        /// </summary>
        internal static string DescribeWhere {
            get {
                return ResourceManager.GetString("DescribeWhere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Watching needs a console to paint on..
        /// </summary>
        internal static string MonitorNeedsConsole {
            get {
                return ResourceManager.GetString("MonitorNeedsConsole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}, {1}, Ctrl+C stops..
        /// </summary>
        internal static string MonitorHeaderWithKey {
            get {
                return ResourceManager.GetString("MonitorHeaderWithKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [C]lose [R]estart [T]erminate everything, [K] to pick.
        /// </summary>
        internal static string LockMonitorKeys {
            get {
                return ResourceManager.GetString("LockMonitorKeys", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to K.
        /// </summary>
        internal static string ActionChooseKey {
            get {
                return ResourceManager.GetString("ActionChooseKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}, Ctrl+C stops..
        /// </summary>
        internal static string MonitorHeader {
            get {
                return ResourceManager.GetString("MonitorHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid interval: {0}.
        /// </summary>
        internal static string InvalidInterval {
            get {
                return ResourceManager.GetString("InvalidInterval", resourceCulture);
            }
        }
    }
}
